# config/settings.yml

discord:
  # Discordで取得したWebhook URLをここに貼り付けます
  webhook_url: "https://discord.com/api/webhooks/1402134851796078694/sXYD94uOx7OuyvTY7ED___6qwbGU5ii3Qi73D5-4svVPEjvT_ru_bzgc_zF0vOHAlZOF"

schedule:
  # 通知を送りたい時刻 (例: "18:00")
  time: "10:08"
  # 送りたいメッセージ
  message: "@ソフト 進捗どうですか？"
